travis:
  secure:
    BINSTAR_TOKEN: eZoOjMjRHKG/BWX9mKjROxMhsBPLjsFgOkDpbE/LNm8N6Bz5MlXMNHZIrFO5pEBJFfii1FxNPMhcHjtIbT4Gjn+lE1lmPp2DwzNisbBwR8PvvqNtKyqreZjFHo8jacVnkXFs/83J7tMTqwvgICb3ZQ0ZhxXSXCAt8oEqCJtahr3jITplu3UA0QYvg2PWFgn11MwoRf8aKOGyMjxL6ddKd1PwsEoP+3AjTUWiDb8JZwfp97F9sG+uw5bV6cPgV7XUOAVWdoOXkzkD1PaiMN9UF0dU8PmuYx0a6wq/yYgoU9EIx4p3bRAEuflwDxnmfdjLWIjxC2icEme2T+Jd/00pPkbO8ZutsevvZ+FcIvMayzxx8A9bUxfk7EUrcZSe4aDgcO91jOKtR5I87u8lwdr9pxnQkOC1vkrq1hzd66ttnEsZwibpjcOUeLVSIFCezBSNHytfc1OdPWRy1lvfFS0EnYHG6E2HCpep0CdCFj6L3PQ3v/3FnnS59euH7uJQrzLKwSHkN6F7vagIW7eVdC2sYnUiR2kv9b54++WA8xUv9H95baghi4Kh4hZLtzJeuoaSBtAnmxpFZgH8Hrpue3F1m6ClHAHvEoNResA4TFQqF5KTouP//ZJzRSZ25u8Nd6lZD63VTPsJ7RKhfySIV/sn7IExfPxhGNn1vNZ8srsnv4w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
